# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.TextField(max_length=20)),
                ('Lost_Found_Product', models.TextField(max_length=20)),
                ('Small_Description', models.TextField(max_length=120)),
                ('Tags', models.CharField(max_length=50)),
                ('Location', models.TextField()),
                ('Date_and_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
