# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostNFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Lost_Found_Product', models.CharField(max_length=10)),
                ('Small_Description', models.TextField(max_length=120)),
                ('Location', models.TextField()),
                ('Date_and_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_Page',
        ),
    ]
