# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0002_auto_20180920_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostnfound',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
