# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnf', '0003_lostnfound_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostnfound',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lostnfound',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lostnfound',
            name='Image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width'),
        ),
    ]
